# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('Batch_No', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Father_Name', models.CharField(max_length=100, null=True)),
                ('Date_of_Training', models.DateField(blank=True, null=True)),
                ('Date_of_Joining', models.DateField(blank=True, null=True)),
                ('Date_of_Ending', models.DateField(blank=True, null=True)),
                ('Distribution_Center', models.CharField(max_length=100, null=True)),
                ('Batch_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.Batch')),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.Courses'),
        ),
    ]
