# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-04 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Date_of_Training',
            new_name='Date_of_Order_Issue',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Distribution_Center',
            new_name='Name_of_Division',
        ),
        migrations.AddField(
            model_name='person',
            name='Document_No',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='File_No',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Order_No',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Rack_No',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
