# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_auto_20180707_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='')),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.Courses')),
            ],
        ),
    ]
