# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
