# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-10 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
    ]
