# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_remove_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='images',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
