# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_courses_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Image', models.FileField(default='', upload_to='')),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Contact_No', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.Courses')),
            ],
        ),
    ]
